dist: xenial
addons:
  apt:
    packages:
      - libcunit1
      - libcunit1-doc
      - libcunit1-dev
      - libgsl-dev

install:
  - ./scripts/install_flame.sh
  - (cd xparser && ./xparser ../eurace_model.xml)
  - sed -i 's|= /usr/local/lib|= $(PWD)/libmboard|g' Makefile
  - make

script:
  - ./run_tests.sh
