dist: xenial
addons:
  apt:
    packages:
      - libcunit1
      - libcunit1-doc
      - libcunit1-dev
      - libgsl-dev

install:
  - wget https://github.com/FLAME-HPC/libmboard/archive/0.3.1.zip
  - unzip 0.3.1.zip
  - mkdir libmboard
  - cd libmboard-0.3.1
  - chmod +x autogen.sh
  - ./autogen.sh
  - ./configure --prefix=$(cd ../libmboard; pwd) --disable-parallel
  - make
  - make install
  - cd ..
  - wget https://github.com/FLAME-HPC/xparser/archive/0.17.1.tar.gz
  - tar xf 0.17.1.tar.gz
  - mv xparser-0.17.1 xparser
  - cd xparser
  - make
  - ./xparser ../eurace_model.xml
  - cd ..
  - sed -i 's|= /usr/local/lib|= $(PWD)/libmboard|g' Makefile
  - make

script:
  - ./run_tests.sh
